apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: backupjob
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
      - pods/exec
    verbs:
      - '*'