apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: backupjob
roleRef:
  name: backupjob
subjects:
  - kind: ServiceAccount
    name: backupjob
    namespace: default
