---
apiVersion: v1
kind: Template
metadata:
  name: "integreatly-job-backup-template"
  annotations:
    description: 'Job for backing up integreatly data on demand'
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${NAME}
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: ${NAME}
          labels:
            job-name: ${NAME}
        spec:
          serviceAccountName: "${SERVICEACCOUNT}"
          containers:
            - name: backup-job
              image: "${IMAGE}"
              imagePullPolicy: Always
              command:
                - "/opt/intly/tools/entrypoint.sh"
                - "-c"
                - "${COMPONENT}"
                - '-b'
                - "${BACKEND}"
                - "-e"
                - "${ENCRYPTION}"
                - "-d"
                - "${DEBUG}"
              env:
                - name: BACKEND_SECRET_NAME
                  value: ${BACKEND_SECRET_NAME}
                - name: ENCRYPTION_SECRET_NAME
                  value: ${ENCRYPTION_SECRET_NAME}
              envFrom:
                - secretRef:
                    name: "${COMPONENT_SECRET_NAME}"
          restartPolicy: Never
parameters:
  - name: NAME
    description: Unique job name to be used in several resource name(s)
    value: integreatly-job-backup
  - name: COMPONENT
    description: Component name to run the backup
    required: true
  - name: BACKEND
    description: Backend engine to upload the component archive
    value: s3
  - name: ENCRYPTION
    description: Encryption engine to encrypt component archive before uploading it
    value: gpg
  - name: COMPONENT_SECRET_NAME
    description: Component secret name to create environment variables from
    required: true
    value: dummy
  - name: BACKEND_SECRET_NAME
    description: Backend secret name to create environment variables from
    required: true
    value: s3-credentials
  - name: ENCRYPTION_SECRET_NAME
    description: Encruption secret name to create environment variables from
    required: true
    value: gpg-credentials
  - name: IMAGE
    description: 'Backup docker image URL'
    value: 'quay.io/integreatly/backup-container:master'
  - name: SERVICEACCOUNT
    description: 'The service account used by the backup job'
    value: backupjob
  - name: DEBUG
    description: "Debug flag to sleep the job pod after its execution"
